// Moxon 868 MHz frame - OpenSCAD reconstruction
// Reconstructed as native polyhedron data from the STL triangle mesh.
// Units: millimeters

/* [Transform] */
position_mm = [0, 0, 0];
rotation_deg = [0, 0, 0];
scale_xyz = [1, 1, 1];

/* [Mesh options] */
repair_faces = false; // Enable if your OpenSCAD build reports orientation issues.

// Reusable mesh dataset generated by: tools/stl_to_scad_polyhedron.py
include <moxon_868mhz_mesh_data.scad>

module moxon_mesh(points = mesh_points, faces = mesh_faces, repair = repair_faces) {
  polyhedron(points = points, faces = faces, convexity = 10);
}

module moxon_868_reconstruction(pos = position_mm,
                                rot = rotation_deg,
                                scl = scale_xyz,
                                repair = repair_faces) {
  translate(pos)
    rotate(rot)
      scale(scl)
        moxon_mesh(repair = repair);
}

moxon_868_reconstruction();
