#!/usr/bin/env python3
"""Convert binary/ASCII STL mesh to OpenSCAD polyhedron data.

Reusable utility:
- Deduplicates vertices with configurable rounding precision.
- Emits compact OpenSCAD arrays (`mesh_points`, `mesh_faces`).
"""
from __future__ import annotations
import argparse
import struct
from pathlib import Path


def read_binary_stl(path: Path):
    with path.open('rb') as f:
        f.read(80)
        tri_count = struct.unpack('<I', f.read(4))[0]
        vertices = []
        for _ in range(tri_count):
            f.read(12)  # normal
            tri = []
            for _ in range(3):
                tri.append(struct.unpack('<3f', f.read(12)))
            f.read(2)  # attr
            vertices.append(tri)
    return vertices


def convert(tris, precision: int):
    idx = {}
    points = []
    faces = []
    for tri in tris:
        face = []
        for v in tri:
            key = tuple(round(c, precision) for c in v)
            if key not in idx:
                idx[key] = len(points)
                points.append([float(key[0]), float(key[1]), float(key[2])])
            face.append(idx[key])
        if len(set(face)) == 3:
            faces.append(face)
    return points, faces


def write_scad(out: Path, points, faces):
    with out.open('w', encoding='utf-8') as f:
        f.write('// Auto-generated by tools/stl_to_scad_polyhedron.py\n')
        f.write(f'mesh_points = [\n')
        for p in points:
            f.write(f'  [{p[0]:.6f}, {p[1]:.6f}, {p[2]:.6f}],\n')
        f.write('];\n\n')
        f.write('mesh_faces = [\n')
        for a, b, c in faces:
            f.write(f'  [{a}, {b}, {c}],\n')
        f.write('];\n')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('input_stl', type=Path)
    ap.add_argument('output_scad', type=Path)
    ap.add_argument('--precision', type=int, default=5)
    args = ap.parse_args()

    tris = read_binary_stl(args.input_stl)
    points, faces = convert(tris, args.precision)
    write_scad(args.output_scad, points, faces)
    print(f'Wrote {len(points)} points and {len(faces)} faces to {args.output_scad}')


if __name__ == '__main__':
    main()
